package com.systemprevention.api.model;

public enum TipoGolpe {
    FALSA_CENTRAL_ATENDIMENTO,
    FALSO_ALERTA_SEGURANCA,
    FALSO_BLOQUEIO_CONTA,
    FALSA_REGULARIZACAO_CONTA,

    PHISHING_LINK_FALSO,
    SITE_FALSO_BANCO,
    SMISHING_SMS_FALSO,
    GOLPE_WHATSAPP,

    GOLPE_PIX,
    FALSO_COMPROVANTE_PIX,
    FALSA_DEVOLUCAO_PIX,

    FALSO_BOLETO,
    FALSA_RENEGOCIACAO_DIVIDA,
    FALSA_COBRANCA_BANCARIA,

    COMPRA_NAO_RECONHECIDA,
    CARTAO_CLONADO,
    USO_INDEVIDO_CARTAO,
    TROCA_OU_RETENCAO_CARTAO,

    FALSA_ATUALIZACAO_CADASTRAL,
    FALSO_TOKEN_OU_CODIGO,
    FALSO_SUPORTE_TECNICO,
    INSTALACAO_APP_MALICIOSO,

    FALSO_EMPRESTIMO,
    ROUBO_CELULAR_ACESSO_CONTA,
    ENGENHARIA_SOCIAL,
    OUTRO
}